// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtvMn-VbuSOSYtZI7GLc2v5OWkmQAEFns',
    appId: '1:766939121362:web:430ed91938ccdfd4ebcf0b',
    messagingSenderId: '766939121362',
    projectId: 'move-sketch',
    authDomain: 'move-sketch.firebaseapp.com',
    storageBucket: 'move-sketch.firebasestorage.app',
    measurementId: 'G-1C53CMQ50Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBllmzsyxF1ulUdPUm7IKAoBGcQi-O2h-4',
    appId: '1:766939121362:android:cf933493bdc03098ebcf0b',
    messagingSenderId: '766939121362',
    projectId: 'move-sketch',
    storageBucket: 'move-sketch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvvEDCeehO477QltOJX0y8vZVx8c34gLo',
    appId: '1:766939121362:ios:3aadae7dbfdbadf8ebcf0b',
    messagingSenderId: '766939121362',
    projectId: 'move-sketch',
    storageBucket: 'move-sketch.firebasestorage.app',
    iosBundleId: 'com.neonsigntrap.moveSketch',
  );
}
